/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Ic:baselineDisabledByDefault': typeof import('~icons/ic/baseline-disabled-by-default')['default']
    'MaterialSymbols:selectWindow': typeof import('~icons/material-symbols/select-window')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stratagem: typeof import('./components/stratagem.vue')['default']
    StratagemByName: typeof import('./components/stratagem-by-name.vue')['default']
  }
}
